spring:
  application:
    name: spring-oracle-stored-proc
  datasource:
    username: pivotal
    password: bekind
    url: "jdbc:oracle:thin:@//localhost/ORCLPDB1.localdomain"
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        proc.param_null_passing: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect

management:
  security:
    enabled: false
security:
  basic:
    enabled: false


#mvn install:install-file -Dfile=ojdbc8.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.2.0.1.0 -Dpackaging=jar
